apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: helmrepository-access-global
rules:
  - apiGroups: ["source.toolkit.fluxcd.io"]
    resources: ["helmrepositories"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: helmrepository-binding-global
subjects:
  - kind: ServiceAccount
    name: tenant-root
    namespace: tenant-root
roleRef:
  kind: ClusterRole
  name: helmrepository-access-global
  apiGroup: rbac.authorization.k8s.io

