---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: vmalert
spec:
  endpoints:
  - path: /metrics
    port: http
    relabelConfigs:
    - sourceLabels: [__meta_kubernetes_pod_node_name]
      targetLabel: node
  selector:
    matchLabels:
      app.kubernetes.io/component: monitoring
      app.kubernetes.io/instance: vmalert
      app.kubernetes.io/name: vmalert
