{{- if .Values.registrySecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-regsecret
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {{- toJson .Values.registrySecret | nindent 4 }}
{{- end }}
