apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata: 
  name: {{ .Release.Namespace }}-{{ .Release.Name }}-kccm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Namespace }}-{{ .Release.Name }}-kccm
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-kccm
  namespace: {{ .Release.Namespace }}
