---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: 
  name: {{ .Release.Namespace }}-{{ .Release.Name }}-kccm
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-kccm
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: 
  name: {{ .Release.Name }}-kccm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-kccm
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-kccm
  namespace: {{ .Release.Namespace }}
